-- Seed default feature importance scores
INSERT INTO feature_importance (attribute, place_type, importance_score) VALUES
    ('continent',      'all',       0.95),
    ('subRegion',      'all',       0.90),
    ('type',           'all',       0.98),
    ('subtype',        'all',       0.88),
    ('country',        'all',       0.92),
    ('landlocked',     'country',   0.80),
    ('isIsland',       'all',       0.85),
    ('isArchipelago',  'all',       0.88),
    ('hasMountains',   'country',   0.75),
    ('hasRivers',      'country',   0.70),
    ('hasCoast',       'country',   0.72),
    ('climate',        'all',       0.78),
    ('population',     'country',   0.82),
    ('mainReligion',   'country',   0.88),
    ('language',       'country',   0.90),
    ('government',     'country',   0.85),
    ('driveSide',      'country',   0.75),
    ('hasNobel',       'country',   0.70),
    ('hasUNESCO',      'all',       0.65),
    ('hasWonder',      'all',       0.72),
    ('exports',        'country',   0.75),
    ('famousFor',      'all',       0.85),
    ('neighbors',      'country',   0.80),
    ('capital',        'country',   0.95),
    ('currency',       'country',   0.88),
    ('colonizedBy',    'country',   0.78),
    ('elevation_m',    'geographic', 0.90),
    ('length_km',      'geographic', 0.85),
    ('area_km2',       'all',       0.80),
    ('located_in',     'all',       0.92),
    ('built_year',     'landmark',  0.70),
    ('religion_type',  'religious', 0.90)
ON CONFLICT (attribute, place_type) DO NOTHING;